services:
  server:
    image: ${CTHULHU_MYTHOS_TOOLS_IMAGE}
    restart: unless-stopped
    container_name: cthulhu_mythos
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
    ports:
      - 8080:8080
    networks:
      - cthulhu_mythos

  logs:
    image: 'amir20/dozzle:v6.2.4'
    restart: unless-stopped
    container_name: cthulhu_mythos-logs
    environment:
      DOZZLE_ADDR: ':9999'
      DOZZLE_BASE: /
      DOZZLE_LEVEL: debug
      DOZZLE_TAILSIZE: 300
      DOZZLE_USERNAME: ''
      DOZZLE_PASSWORD: ''
      DOZZLE_KEY: ''
      DOZZLE_FILTER: ''
      DOZZLE_NO_ANALYTICS: 'true'
      DOZZLE_ENABLE_ACTIONS: 'false'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9999:9999'
    expose:
      - 9999
    networks:
      - cthulhu_mythos

networks:
  cthulhu_mythos:
    driver: bridge